name: solace_ai
description: "A private, on-device AI journaling sanctuary built with Flutter."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.47.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking & File Management
  dio: ^5.7.0
  path_provider: ^2.1.5
  path: ^1.9.1

  # On-Device AI
  flutter_gemma: ^1.11.2
  flutter_gemma_mediapipe: ^1.0.6

  # Local Persistence
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.9
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
