import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'context_builder.dart';
import 'json_parser.dart';
import 'local_ai.dart';
import 'prompts.dart';

import 'package:flutter_gemma/flutter_gemma.dart';
import 'package:flutter_gemma_mediapipe/flutter_gemma_mediapipe.dart';

/// On-device AI engine utilizing Google Gemma 3 1B IT via MediaPipe.
class GemmaAi implements LocalAi {
  static const String modelFileName = 'gemma3-1b-it-int4.task';

  final String? customModelPath;
  String? _resolvedModelPath;
  bool _isReady = false;

  GemmaAi({String? modelPath}) : customModelPath = modelPath;

  @override
  String get engineName => 'Gemma 3 1B (on-device)';

  /// Path to the active model task file.
  String? get activeModelPath => _resolvedModelPath ?? customModelPath;

  @override
  Future<bool> init() async {
    try {
      String targetPath;
      if (customModelPath != null && customModelPath!.trim().isNotEmpty) {
        targetPath = customModelPath!;
      } else {
        final appDir = await getApplicationDocumentsDirectory();
        targetPath = '${appDir.path}/$modelFileName';
      }

      final file = File(targetPath);
      final exists = await file.exists();
      if (!exists) {
        _isReady = false;
        return false;
      }

      _resolvedModelPath = targetPath;

      await FlutterGemma.initialize(inferenceEngines: const [MediaPipeEngine()]);
      await FlutterGemma.installModel(modelType: ModelType.gemmaIt)
          .fromFile(targetPath)
          .install();

      _isReady = true;
      return true;
    } catch (_) {
      _isReady = false;
      return false;
    }
  }

  @override
  Future<AiResult> reflect(String entry, UserContext ctx) async {
    if (!_isReady) {
      return AiResult(
        reflection: '',
        engineUsed: engineName,
        usedModel: false,
        error: 'Gemma engine is not initialized or model file is unavailable.',
      );
    }

    try {
      final contextBlock = ContextBuilder.buildContextSummary(ctx);
      final prompt = Prompts.buildReflectionPrompt(
        entry,
        contextBlock: contextBlock.isNotEmpty ? contextBlock : null,
      );

      final rawResponse = await _runInference(prompt);
      if (rawResponse == null || rawResponse.trim().isEmpty) {
        return AiResult(
          reflection: '',
          engineUsed: engineName,
          usedModel: false,
          error: 'Empty response generated by Gemma model.',
        );
      }

      final cleanedReflection = _cleanReflectionResponse(rawResponse);

      return AiResult(
        reflection: cleanedReflection,
        engineUsed: engineName,
        usedModel: true,
      );
    } catch (e) {
      return AiResult(
        reflection: '',
        engineUsed: engineName,
        usedModel: false,
        error: 'Inference failure: $e',
      );
    }
  }

  @override
  Future<AiResult> compareOptions(String entry, UserContext ctx) async {
    if (!_isReady) {
      return AiResult(
        reflection: '',
        engineUsed: engineName,
        usedModel: false,
        error: 'Gemma engine is not initialized or model file is unavailable.',
      );
    }

    try {
      final contextBlock = ContextBuilder.buildContextSummary(ctx);
      final related = ContextBuilder.getTruncatedRelatedEntries(ctx);

      final prompt = Prompts.buildDecisionPrompt(
        entry: entry,
        priorities: ctx.priorities,
        relatedEntries: related,
        contextBlock: contextBlock.isNotEmpty ? contextBlock : null,
      );

      String? rawResponse = await _runInference(prompt);
      AiResult? parsed = JsonParser.parseAiResult(
        rawResponse,
        engineUsed: engineName,
        usedModel: true,
      );

      // If initial JSON parsing failed, retry once with explicit JSON instruction
      if (parsed == null) {
        final retryPrompt =
            '$prompt\n\n${Prompts.jsonRetryInstruction}\nPrevious response was invalid JSON.';
        rawResponse = await _runInference(retryPrompt);
        parsed = JsonParser.parseAiResult(
          rawResponse,
          engineUsed: engineName,
          usedModel: true,
        );
      }

      if (parsed == null) {
        return AiResult(
          reflection: '',
          engineUsed: engineName,
          usedModel: false,
          error: 'Model produced invalid JSON output after retry.',
        );
      }

      return parsed;
    } catch (e) {
      return AiResult(
        reflection: '',
        engineUsed: engineName,
        usedModel: false,
        error: 'Decision inference failure: $e',
      );
    }
  }

  Future<String?> _runInference(String prompt) async {
    final model = await FlutterGemma.getActiveModel(maxTokens: 512);
    final session = await model.createSession();
    await session.addQueryChunk(Message(text: prompt, isUser: true));
    return await session.getResponse();
  }

  String _cleanReflectionResponse(String raw) {
    return raw.trim().replaceAll(RegExp(r'\n+'), ' ');
  }
}
