import 'dart:io';
import 'context_builder.dart';
import 'json_parser.dart';
import 'local_ai.dart';
import 'prompts.dart';

// TODO: needs flutter_gemma dependency in pubspec.yaml
// dependencies:
//   flutter_gemma: ^1.11.2
//   flutter_gemma_mediapipe: ^1.0.6
//
// When flutter_gemma is present in pubspec.yaml, uncomment:
// import 'package:flutter_gemma/flutter_gemma.dart';
// import 'package:flutter_gemma_mediapipe/flutter_gemma_mediapipe.dart';

/// On-device AI engine utilizing Google Gemma 3 1B IT via MediaPipe.
class GemmaAi implements LocalAi {
  /// Default sideload path for the int4 quantized Gemma 3 model on Android.
  static const String defaultModelPath =
      '/storage/emulated/0/Download/gemma3-1b-it-int4.task';

  final String modelPath;
  bool _isReady = false;

  GemmaAi({this.modelPath = defaultModelPath});

  @override
  String get engineName => 'Gemma 3 1B (on-device)';

  @override
  Future<bool> init() async {
    try {
      final file = File(modelPath);
      final exists = await file.exists();
      if (!exists) {
        _isReady = false;
        return false;
      }

      // TODO: needs flutter_gemma dependency
      // Once dependencies are added, initialize MediaPipe and register model:
      // await FlutterGemma.initialize(inferenceEngines: const [MediaPipeEngine()]);
      // await FlutterGemma.installModel(modelType: ModelType.gemmaIt)
      //     .fromFile(modelPath)
      //     .install();

      _isReady = true;
      return true;
    } catch (_) {
      _isReady = false;
      return false;
    }
  }

  @override
  Future<AiResult> reflect(String entry, UserContext ctx) async {
    if (!_isReady) {
      return AiResult(
        reflection: '',
        engineUsed: engineName,
        usedModel: false,
        error: 'Gemma engine is not initialized or model file is unavailable.',
      );
    }

    try {
      final contextBlock = ContextBuilder.buildContextSummary(ctx);
      final prompt = Prompts.buildReflectionPrompt(
        entry,
        contextBlock: contextBlock.isNotEmpty ? contextBlock : null,
      );

      final rawResponse = await _runInference(prompt);
      if (rawResponse == null || rawResponse.trim().isEmpty) {
        return AiResult(
          reflection: '',
          engineUsed: engineName,
          usedModel: false,
          error: 'Empty response generated by Gemma model.',
        );
      }

      final cleanedReflection = _cleanReflectionResponse(rawResponse);

      return AiResult(
        reflection: cleanedReflection,
        engineUsed: engineName,
        usedModel: true,
      );
    } catch (e) {
      return AiResult(
        reflection: '',
        engineUsed: engineName,
        usedModel: false,
        error: 'Inference failure: $e',
      );
    }
  }

  @override
  Future<AiResult> compareOptions(String entry, UserContext ctx) async {
    if (!_isReady) {
      return AiResult(
        reflection: '',
        engineUsed: engineName,
        usedModel: false,
        error: 'Gemma engine is not initialized or model file is unavailable.',
      );
    }

    try {
      final contextBlock = ContextBuilder.buildContextSummary(ctx);
      final related = ContextBuilder.getTruncatedRelatedEntries(ctx);

      final prompt = Prompts.buildDecisionPrompt(
        entry: entry,
        priorities: ctx.priorities,
        relatedEntries: related,
        contextBlock: contextBlock.isNotEmpty ? contextBlock : null,
      );

      String? rawResponse = await _runInference(prompt);
      AiResult? parsed = JsonParser.parseAiResult(
        rawResponse,
        engineUsed: engineName,
        usedModel: true,
      );

      // If initial JSON parsing failed, retry once with explicit JSON instruction
      if (parsed == null) {
        final retryPrompt =
            '$prompt\n\n${Prompts.jsonRetryInstruction}\nPrevious response was invalid JSON.';
        rawResponse = await _runInference(retryPrompt);
        parsed = JsonParser.parseAiResult(
          rawResponse,
          engineUsed: engineName,
          usedModel: true,
        );
      }

      if (parsed == null) {
        return AiResult(
          reflection: '',
          engineUsed: engineName,
          usedModel: false,
          error: 'Model produced invalid JSON output after retry.',
        );
      }

      return parsed;
    } catch (e) {
      return AiResult(
        reflection: '',
        engineUsed: engineName,
        usedModel: false,
        error: 'Decision inference failure: $e',
      );
    }
  }

  Future<String?> _runInference(String prompt) async {
    // TODO: needs flutter_gemma dependency
    // Example flutter_gemma execution:
    // final model = await FlutterGemma.getActiveModel(maxTokens: 512);
    // final session = await model.createSession();
    // return await session.getResponse(prompt: prompt);
    return null;
  }

  String _cleanReflectionResponse(String raw) {
    return raw.trim().replaceAll(RegExp(r'\n+'), ' ');
  }
}
